I_Facility/Controllers/OperatorEntryListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using I_Facility.ServerModel;
using I_Facility.Models;

namespace I_Facility.Controllers
{
    public class OperatorEntryListController : Controller
    {
        private i_facilityEntities1 db = new i_facilityEntities1();

        //public void getmachinedet()
        //{
        //    List<OP> opobj = new List<OP>();
        //    var celldet = db.tblcells.Where(m => m.IsDeleted == 0).OrderByDescending(m => m.CellID).ToList();
        //    foreach (var item in celldet)
        //    {
        //        OP obj = new OP();
        //        var cellid = item.CellID;
        //        obj.cellid = cellid;
        //        var machdet = db.tblmachinedetails.Where(m => m.IsDeleted == 0 && m.CellID == cellid).OrderByDescending(m => m.MachineID).ToList();
        //        List<mc> m1 = new List<mc>();
        //        foreach (var mitem in machdet)
        //        {
        //            mc mobj = new mc();
        //            mobj.machid = mitem.MachineID;
        //            m1.Add(mobj);
        //        }
        //        obj.machdet = m1;
        //        opobj.Add(obj);
        //    }
        //    Session["MachineDetails"] = opobj;
        //}


        // GET: OperatorEntryList
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StoredataStartfun(int OperatorID, string OperatorNo, int ProductionOrderNo, string PartNo, int ProductionOrderQty, int ProcessQty, string Shift, int YieldQty, int ScrapQty, int TotalQty)
        {
            tbloperatorentry optobj = new tbloperatorentry();
            optobj.CorrectedDate = DateTime.Now;
            optobj.CreatedBy = 1;
            optobj.CreatedOn = DateTime.Now;
            optobj.isDeleted = 0;
            optobj.ModifiedBy = 1;
            optobj.ModifiedOn = DateTime.Now;  
            optobj.OperationNo = OperatorNo;
            //optobj.OPID = OperatorID.ToString();
            optobj.PartNo = PartNo;
            optobj.ProcessQty = ProcessQty;
            optobj.ProducationOrderNo = ProductionOrderNo;
            optobj.ProductionOrderQty = ProductionOrderQty;
            optobj.ScrapQty = ScrapQty;
            optobj.Shift = Shift;
            optobj.Total = TotalQty;
            optobj.YieldQty = YieldQty;
            db.tbloperatorentries.Add(optobj);
            db.SaveChanges();
            return RedirectToAction("Index");
            //return View("Index");
        }
        #region V changed

        public int MachineCheck(int machineid)
        {
            var machdet = db.tbllivemodes.Where(m => m.IsDeleted == 0 && m.MachineID == machineid && m.StartIdle == 1 && m.IsCompleted == 0).OrderByDescending(m => m.MachineID).FirstOrDefault();
            if (machdet != null)
            {
                return machdet.MachineID;
            }
            return 0;
        }

        public ActionResult IDLEPopupCell(FormCollection form, int LossSelect = 0, int value = 0)
        {
            //if(value==0)
            //{
            //    getmachinedet();
            //}
            var ob = Session["MachineDetails"];
            var celldet = db.tblcells.Where(m => m.IsDeleted == 0).OrderByDescending(m => m.CellID).ToList();
            foreach (var item in celldet)
            {
                var cellid = item.CellID;
                var machdet = db.tblmachinedetails.Where(m => m.IsDeleted == 0 && m.CellID == cellid).OrderByDescending(m => m.MachineID).ToList();
                foreach (var mitem in machdet)
                {
                    var mid = mitem.MachineID;
                    GetMode GM = new GetMode();
                    //String IPAddress = GM.GetIPAddressofTabSystem();
                    //if (mid == value)
                    //{

                    //}
                    //else
                    //{
                    /* MachineCheck(mitem.MachineID)*/
                    //int MachineID = db.tblmachinedetails.Where(m => m.TabIPAddress == IPAddress && m.IsDeleted == 0).Select(m => m.MachineID).First();
                    var MachineID = db.tblmachinedetails.Where(m => m.MachineID == mid && m.IsDeleted == 0 && m.MachineID != value).OrderByDescending(m => m.MachineID).Select(m => m.MachineID).First();
                    bool flag = GM.CheckIdleEntry(MachineID);
                    if (flag == true)
                    {
                        Session["MachineID"] = MachineID;

                        var prvmode = db.tbllivemodes.Where(m => m.MachineID == MachineID && m.ModeType == "SETUP" && m.ModeTypeEnd == 0).OrderByDescending(m => m.InsertedOn).FirstOrDefault();
                        if (prvmode != null)
                        {
                            ViewBag.SetUpStarted = "1";
                            ViewBag.MachineMode = "Setting";
                        }

                        var prvmodeMaint = db.tbllivemodes.Where(m => m.MachineID == MachineID && m.ModeType == "MNT" && m.ModeTypeEnd == 0).OrderByDescending(m => m.InsertedOn).FirstOrDefault();
                        if (prvmodeMaint != null)
                        {
                            ViewBag.MNTStarted = "1";
                            ViewBag.MachineMode = "MNT";
                        }

                        var tblLossCodes = db.tbllossescodes.Where(m => m.MessageType == "IDLE").ToList();
                        ViewBag.lossCodes = tblLossCodes;

                        if (LossSelect == 0)//first time ,show level 1
                        {
                            int lossCodeID = tblLossCodes.Find(a => a.MessageType == "IDLE").LossCodeID;
                            ViewBag.lossCodeID = lossCodeID;
                            ViewBag.level = 1;
                        }
                        else if (tblLossCodes.Where(m => m.LossCodesLevel1ID == LossSelect).ToList().Count > 0)// show level 2
                        {
                            int lossCodeID = LossSelect;
                            ViewBag.lossCodeID = lossCodeID;
                            ViewBag.level = 2;
                        }
                        else //show level 3
                        {
                            int lossCodeID = LossSelect;
                            ViewBag.lossCodeID = lossCodeID;
                            ViewBag.level = 3;
                        }

                        #region Update tblOperatorHeader 

                        //get the latest row according to the MachineID and CorrectedDate ->  there is no CorrectedDate column 
                        var operatorHeader = db.tbloperatorheaders.Where(m => m.MachineID == MachineID).OrderByDescending(m => m.InsertedOn).FirstOrDefault();
                        if (operatorHeader != null)
                        {
                            operatorHeader.MachineMode = "IDLE";
                            operatorHeader.ModifiedOn = DateTime.Now;
                            operatorHeader.ModifiedBy = 1;// get from session once these screens are integrated....

                            db.Entry(operatorHeader).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                        }
                        #endregion

                        #region Lock the Machine
                        //var MacDet = db.tblmachinedetails.Find(MachineID);

                        //if (MacDet.MachineModelType == 1)
                        //{
                        //    AddFanucMachineWithConn AC = new AddFanucMachineWithConn(MacDet.IPAddress);
                        //    //AC.setmachinelock(true, (ushort)MacDet.MachineLockBit, (ushort)MacDet.MachineIdleBit, (ushort)MacDet.MachineUnlockBit);
                        //}

                        #endregion

                        var HeaderDet = db.tbloperatorheaders.Where(m => m.MachineID == MachineID).SingleOrDefault();
                        var HeaderDet1 = db.tblmachinedetails.Where(m => m.MachineID == MachineID).SingleOrDefault();
                        if (HeaderDet != null)
                        {
                            ViewBag.MachineMode = HeaderDet.MachineMode;
                            ViewBag.MachineName = HeaderDet1.tblcell.CellName;
                            ViewBag.TabStatus = HeaderDet.TabConnecStatus;
                            ViewBag.ServerStatus = HeaderDet.ServerConnecStatus;
                            ViewBag.PageName = "IDLE";
                            ViewBag.Shift = HeaderDet.Shift;

                            return View(new { value = MachineID });
                            //}
                        }
                    }
                    else
                    {

                    }
                }
            }
            return RedirectToAction("DashboardProduction");
        }

        public JsonResult CheckIdle(int value = 0)
        {
            // db.Database.CommandTimeout = 180;
            GetMode GM = new GetMode();
            int Data = 0;

            //String IPAddress = GM.GetIPAddressofTabSystem();
            var celldet = db.tblcells.Where(m => m.IsDeleted == 0).OrderByDescending(m => m.CellID).ToList();
            foreach (var item in celldet)
            {
                var cellid = item.CellID;
                //int MachineID = _ServerContext.tblmachinedetails.Where(m => m.TabIPAddress == IPAddress && m.IsDeleted == 0).Select(m => m.MachineID).First();
                var machdet = db.tblmachinedetails.Where(m => m.IsDeleted == 0 && m.CellID == cellid).OrderByDescending(m => m.MachineID).ToList();
                foreach (var mitem in machdet)
                {
                    //String IPAddress = GM.GetIPAddressofTabSystem();
                    var mid = mitem.MachineID;

I_Facility/Views/OperatorEntryList/DashboardProduction.cshtml
@model I_Facility.Models.OperatorDashboard
@{
    ViewBag.Title = "UnitWorks - VirtualHMI";
    Layout = "~/Views/Shared/_OperatorLayout.cshtml";
    var slno = 1;
}
<input id="SetupError" value="@ViewBag.SetupError" type="hidden" />
<div class="">
    <div class="x_panel">
        <div class="x_content">
            <table id="datatable-fixed-header" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Machine Name</th>
                        <th>Status</th>
                        <th>Description</th>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th>Total Duration (Mins)</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model.OpDashboardList)
                        {
                            <tr>
                                <td>@slno</td>
                                <td>@Html.DisplayFor(modelitem => item.tblmachinedetail.MachineName)</td>
                                <td>@Html.DisplayFor(modelItem => item.MessageCode)</td>
                                <td>@Html.DisplayFor(modelItem => item.MessageDescription)</td>
                                <td>@Html.DisplayFor(modelItem => item.MessageStartTime)</td>
                                @if (item.MessageEndTime.HasValue)
                                {
                                    <td>@Convert.ToDateTime(item.MessageEndTime).ToString("dd-MM-yyyy HH:mm:ss")</td>
                                }
                                else
                                {
                                    <td></td>
                                }
                                <td>@Html.DisplayFor(modelItem => item.TotalDurationinMin)</td>
                            </tr>
                            slno++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

I_Facility/Views/OperatorEntryList/IDLEPopupCell.cshtml
@{
    ViewBag.Title = "IDLEPopupCell";
    Layout = "~/Views/Shared/_OperatorLayout.cshtml";
}

<div class="mp_content">
    <h3>
        IDLE / LOSS Window
    </h3>
    <form method="post" action="/OperatorEntrylist/IDLEPopupCell">
        <div>
            @foreach (var level in ViewBag.lossCodes)
            {
                if (ViewBag.level == 1)
                {
                    if (level.LossCodesLevel == ViewBag.level)
                    {
                        @*<button type="submit" name ="button" class="btn btn-primary"  action="/OperatorEntry/SettingWindow"  value="@level.LossCodeID"> @level.LossCode </button>*@
                        <button type="button" name="buttonlevelOne" class="col-sm-2 col-xs-2 f-s-18 btn btn-primary lossid" onclick="lastNode(@level.LossCodeID, 1)" value="@level.LossCodeID"> @level.LossCode </button>
                    }
                }
                if (ViewBag.level == 2)
                {
                    if (level.LossCodesLevel == ViewBag.level && level.LossCodesLevel1ID == ViewBag.lossCodeID)
                    {
                        @*<button type="submit" name ="button" class="btn btn-primary"  action="/OperatorEntry/SettingWindow"  value="@level.LossCodeID"> @level.LossCode </button>*@
                        <button type="button" name="buttonlevelTwo" class="col-sm-2 col-xs-2 f-s-18 btn btn-primary lossid" onclick="lastNode(@level.LossCodeID, 2)" value="@level.LossCodeID"> @level.LossCode </button>
                    }
                }
                if (ViewBag.level == 3)
                {
                    if (level.LossCodesLevel == ViewBag.level && level.LossCodesLevel2ID == ViewBag.lossCodeID)
                    {
                        <button type="button" name="button" class="col-sm-2 col-xs-2 f-s-18 btn btn-primary lossid" onclick="if (confirm('Are you sure?')) { window.location.href = '@Url.Action("SaveSetting", "OperatorEntry",new {  LossSelect= level.LossCodeID })'; }" value="@level.LossCodeID"> @level.LossCode </button>
                    }
                }
            }
            @if (ViewBag.MachineMode != "Setting" && ViewBag.MachineMode != "MNT")
            {
                @Html.ActionLink("Setting", "SettingWindow", "OperatorEntry", new { @class = "col-sm-2 col-xs-2 btn btn-primary f-s-18" })
                @Html.ActionLink("Maintenance", "MaintenanceWindow", "OperatorEntry", new { @class = "col-sm-2 col-xs-2 btn btn-primary f-s-18" })
            }
            <input type="text" name="LossSelect" id="LossSelect" hidden="hidden" />
        </div>
    </form>
</div>
<!-- jQuery -->
<script src="../vendors/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    function lastNode(LossCodeID, Level) {

        var sorf = "";
        $.ajax({
            type: "POST",
            url: "/OperatorEntryList/ServerPing",
            async: false,
            success: function (data) {
                var status = data;
                if (status == "Connected") {
                    sorf = "Connected";
                }
                else {
                    sorf = "NotConnected";
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //if (textStatus == 'Unauthorized') {
                //    alert('custom message. Error: ' + errorThrown);
                //} else {
                //    alert('custom message. Error: ' + errorThrown);
                //}
                sorf = "NotConnected";
                toastr.warning("", "There is some issue in network");
            }
        });

        if (sorf == "Connected") {
            //unblock();
            $("#LossSelect").val(LossCodeID);
        var dat = JSON.stringify({
            'id': LossCodeID,
            'lev': Level
        });
        var request = '/OperatorEntryList/lastNodeIdleCheck/' + LossCodeID + '?lev=' + Level;
        $.get(
            request,
            function (data) {
                var response = String(data);
                var response = response.split('/');
                var LastNode = response[0].toString();
                var buttonClickID = response[1].toString();
                if (LastNode == "true" ) {
                    if (confirm('Are you sure?')) {
                        window.location.href = '@Url.Action("SaveIdle", "OperatorEntryList")' + '?selectLoss=' + buttonClickID;
                    }
                } else
                {
                  //  $.post('/OperatorEntry/SettingWindow/?l=' + buttonClickID);
                    //window.location.href = '/OperatorEntry/SettingWindow /?l = ' + buttonClickID;
                    //$("form").attr("action", '/OperatorEntry/SettingWindow/?l =' + buttonClickID);
                    $("form").attr("action", '/OperatorEntryList/IDLEPopupCell');
                    $("form").attr("name", "buttonlevelOne");
                    $("form").attr("value", buttonClickID);
                    $("form").attr("mode", "post");
                    $("form").submit();
                }
            });
        }
        else {
            toastr.error("", "No Internet Connectivity");
            //block();
        }


    }
</script>
<script>
    function block() {
        $(".btn").attr('disabled', 'disabled');
    }

    function unblock() {
        $(".btn").removeAttr('disabled', 'disabled');
    }

</script>
<link href="~/Content/toaster.css" rel="stylesheet" />
<script src="~/Scripts/toaster.js"></script>
<script>
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-top-full-width",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "5000",
        "hideDuration": "7000",
        "timeOut": "5000",
        "extendedTimeOut": "5000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };
    toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-top-full-width",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "5000",
        "hideDuration": "7000",
        "timeOut": "5000",
        "extendedTimeOut": "5000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    };
</script>

I_Facility/Views/OperatorEntryList/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_OperatorLayout.cshtml";
}
<!-- Bootstrap -->
<link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<h2 class="text-center">Operator entry</h2>

<div class="text-center col-sm-12" id="opentry">
    <label> Number of Operator : </label><input id="txt1" type="number" class="txtBox text-light text-border" placeholder="Enter Numeric Value" onchange="repettext()" />
</div>
<div class="row" id="opdet">
    <br />
    <div class="text-center">
    <h1 class="text-left" style="margin-left:30px"> Enter Operator Details</h1>
    </div>
    <div class="table"  style="margin-left:30px">
        <div class="row" id="opdetails">
          
                @*<div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            Shift
                        </label>

                        <select class="form-control" tabindex="2">
                            <option value="" selected="" disabled="">Select Shift</option>
                            <option value="United States">Shift 1</option>
                            <option value="United Kingdom">Shift 2</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            Operator ID
                        </label>

                        <input type="text" id="print" name="print" placeholder="Operator ID" class="form-control">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            Production Order No.
                        </label>

                        <input type="text" id="print" name="print" placeholder="Production Order No." class="form-control">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            Operation No.
                        </label>

                        <input type="text" id="print" name="print" placeholder="Operation No." class="form-control">
                    </div>
                </div>
            </div>*@
            @*<div class="row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            FG Code
                        </label>

                        <input type="text" id="print" name="print" placeholder="FG Code" class="form-control">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            Prod. Order Qty
                        </label>

                        <input type="text" id="print" name="print" placeholder="Prod. Order Qty" class="form-control">
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label>
                            Processed Qty
                        </label>

                        <input type="text" id="print" name="print" placeholder="Total" class="form-control">
                    </div>
                </div>
            </div>*@
        </div>
        <br />
        <div class="row">
            <button type="submit" class="storetbl" style="margin-left: 30px;">Start</button>
        </div>
    </div>
</div>

<script src="~/js/jquery-2.1.4.min.js"></script>
<script>
    function repettext() {
        $("#opdetails").html('');
        var counter = document.getElementById("txt1").value;
        for (i = 1; i <= counter; i++) {
            $("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group col-sm-3'><label style='margin-left: 30px;' >Shift </label>  <input type='text' id='txtShift" + i + "' class='txtBoxShift' /></div> </div><div class='col-sm-3'><div class='form-group'><label  style='margin-left: 30px;'>Operator ID </label> <input type='text' id='txtOperatorID" + i + "' class='txtBoxOperatorID' required /> </div></div><div class='col-sm-3'><div class='form-group'><label> Production Order No </label> <input type='text' id='txtProductionOrderNo" + i + "' class='txtBoxProductionOrderNo' /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Operator No </label> <input type='text' id='txtOperatorNo" + i + "' class='txtBoxOperatorNo' required /> </div></div></div>");
            $("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'>Part No </label> <input type='text' id='txtBoxPartNo" + i + "' class='txtBoxPartNo' style='margin-left: 15px;' /> </div></div><div class='col-sm-3'><div class='form-group'><label>Production Order Qty</label> <input type='text' id='txtProductionOrderQty" + i + "' class='txtBoxProductionOrderQty' /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Process Qty </label> <input type='text' id='txtProcessQty" + i + "' class='txtBoxProcessQty' /> </div></div></div>");
            $("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group'><label style='margin-left: 15px;'><label style='margin-left: 10px;'> Yield Qty &nbsp;&nbsp;</label> <input type='text' id='txtYieldQty" + i + "' class='txtBoxYieldQty' style='width: 175px;' /></div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'>Scrap Qty </label> <input type='text' id='txtScrapQty" + i + "' class='txtBoxScrapQty' /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Total Qty &nbsp;&nbsp;</label> <input type='text' id='txtTotalQty" + i + "' class='txtBoxTotalQty' /> </div></div></div>");


            //$("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group'><h3><label style='margin-left: 30px;'> Operator '" + i +"'</label></h3></div></div></div>");
            //$("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group'><label  style='margin-left: 30px;'>Operator ID </label> <input type='text' id='txtOperatorID" + i + "' class='txtBoxOperatorID' required /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Operator No :</label> <input type='text' id='txtOperatorNo" + i + "' class='txtBoxOperatorNo' required /> </div></div><div class='col-sm-3'><div class='form-group'><label> Production Order No :</label> <input type='text' id='txtProductionOrderNo" + i + "' class='txtBoxProductionOrderNo' /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 50px;'>Part No :</label> <input type='text' id='txtBoxPartNo" + i + "' class='txtBoxPartNo' /> </div></div></div>");
            //$("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'>Scrap Qty &nbsp;&nbsp;:</label> <input type='text' id='txtScrapQty" + i + "' class='txtBoxScrapQty' /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Process Qty :</label> <input type='text' id='txtProcessQty" + i + "' class='txtBoxProcessQty' /> </div></div><div class='col-sm-3'><div class='form-group'><label>Production Order Qty:</label> <input type='text' id='txtProductionOrderQty" + i + "' class='txtBoxProductionOrderQty' /> </div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 60px;'>Shift :</label> <input type='text' id='txtShift" + i + "' class='txtBoxShift' /> </div></div></div>");
            //$("#opdetails").append("<div class='row'><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Yield Qty &nbsp;&nbsp;&nbsp;:</label> <input type='text' id='txtYieldQty" + i + "' class='txtBoxYieldQty' /></div></div><div class='col-sm-3'><div class='form-group'><label style='margin-left: 30px;'> Total Qty &nbsp;&nbsp;&nbsp;&nbsp;&nbsp :</label> <input type='text' id='txtTotalQty" + i + "' class='txtBoxTotalQty' /> </div></div></div>");



            //$("#opdetails").append("<div class='det'><div class='opd'><div class='col-sm-3'><label  style='margin-left: 30px;'>Operator ID :</label> <input type='text' id='txtOperatorID" + i + "' class='txtBoxOperatorID' required /> </div>");
            //$("#opdetails").append("<div class='col-sm-3'><label> Operator No :</label> <input type='text' id='txtOperatorNo" + i + "' class='txtBoxOperatorNo' /> </div>");
            //$("#opdetails").append("<div class='col-sm-3'><label> Production Order No :</label> <input type='text' id='txtProductionOrderNo" + i + "' class='txtBoxProductionOrderNo' /></div> ");
            //$("#opdetails").append("<div class='col-sm-3'><label>Part No :</label> <input type='text' id='txtBoxPartNo" + i + "' class='txtBoxPartNo' /></div>");
            //$("#opdetails").append("<div class='col-sm-3'><label style='margin-left: 30px;'>Scrap Qty &nbsp;&nbsp;:</label> <input type='text' id='txtScrapQty" + i + "' class='txtBoxScrapQty' /> </div>");
            //$("#opdetails").append("<div class='col-sm-3'><label> Process Qty :</label> <input type='text' id='txtProcessQty" + i + "' class='txtBoxProcessQty' /> </div> ");
            //$("#opdetails").append("<div class='col-sm-3'><label>Production Order Qty:</label> <input type='text' id='txtProductionOrderQty" + i + "' class='txtBoxProductionOrderQty' /> </div>");
            //$("#opdetails").append("<div class='col-sm-3'><label>Shift &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:</label> <input type='text' id='txtShift" + i + "' class='txtBoxShift' /> </div>");
            //$("#opdetails").append("<div class='col-sm-6'><label style='margin-left: 30px;'> Yield Qty &nbsp;&nbsp;&nbsp;:</label> <input type='text' id='txtYieldQty" + i + "' class='txtBoxYieldQty' /> </div>");
            //$("#opdetails").append("<div class='col-sm-6'><label> Total Qty &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :</label> <input type='text' id='txtTotalQty" + i + "' class='txtBoxTotalQty' /> </div> </div>");
            //$("#det").append("<div class='col-sm-12'><label hidden='hidden'>test</label></div>");
            ////$("#det").append("<div class='col-sm-6'></div>");
        }
        $("#opdet").show();
    }
</script>
<script type="text/javascript">
    $(function () {
        $(document).on('click', '.storetbl', function (e) {
            var counter = document.getElementById("txt1").value;
            for (i = 1; i <= counter; i++) {
                var OperatorID = $("#txtOperatorID" + i).val();
                var OperatorNo = $("#txtOperatorNo" + i).val();
                var ProductionOrderNo = $("#txtProductionOrderNo" + i).val();
                var PartNo = $("#txtBoxPartNo" + i).val();
                var ProductionOrderQty = $("#txtProductionOrderQty" + i).val();
                var ProcessQty = $("#txtProcessQty" + i).val();
                var Shift = $("#txtShift" + i).val();
                var YieldQty = $("#txtYieldQty" + i).val();
                var ScrapQty = $("#txtScrapQty" + i).val();
                var TotalQty = $("#txtTotalQty" + i).val();
                if (OperatorID != "" && OperatorNo != "" && ProductionOrderNo != "" && PartNo != "" && ProductionOrderQty != "" && ProcessQty != "" && Shift != "" && YieldQty != "" && ScrapQty != "" && TotalQty != "") {
                    $.getJSON("/OperatorEntryList/StoredataStartfun", { OperatorID: OperatorID, OperatorNo: OperatorNo, ProductionOrderNo: ProductionOrderNo, PartNo: PartNo, ProductionOrderQty: ProductionOrderQty, ProcessQty: ProcessQty, Shift: Shift, YieldQty: YieldQty, ScrapQty: ScrapQty, TotalQty: TotalQty })
                    window.location.href = '@Url.Action("DashboardProduction", "OperatorEntryList")';
                }
                else {
                    alert("Please Fill all the fields");
                    window.location.href = '@Url.Action("Index", "OperatorEntryList")';
                }
            }

        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#opdet").hide();
    });
</script>