I_Facility/Models/PmCheckPoint.cs
using I_Facility.ServerModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace I_Facility.ServerModel
{
    public class PmCheckPoint
    {
        public tblpmcheckpoint pmCheckPoint { get; set; }
        public IEnumerable<tblpmcheckpoint> pmCheckPointlist { get; set; }
    }
}

I_Facility/Controllers/PmCheckPointController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using I_Facility.ServerModel;
using System.Data.Entity;
using System.Data;
using I_Facility.Models;


namespace I_Facility.Controllers
{
    public class PmCheckPointController : Controller
    {
        i_facilityEntities1 db = new i_facilityEntities1();
        // GET: PmCheckPoint
        public ActionResult Index()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            PmCheckPoint tblpm = new PmCheckPoint();
            tblpm.pmCheckPointlist = db.tblpmcheckpoints.Where(m => m.Isdeleted == 0).ToList();
            return View(tblpm);
        }
        public ActionResult Create()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.plant = new SelectList(db.tblplants.ToList().Where(p => p.IsDeleted == 0), "PlantID", "PlantName").ToList();
            ViewBag.shop = new SelectList(db.tblshops.ToList().Where(d => d.IsDeleted == 0), "ShopId", "ShopName").ToList();
            ViewBag.cell = new SelectList(db.tblcells.ToList().Where(d => d.IsDeleted == 0), "CellID", "CellName").ToList();
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            return View();
        }
       
        public JsonResult InsertData(int Plant, int shop, int cell, string Value, string CheckList, string Frequency, string TypeOfCheckPoint,string How)
        {
            tblpmcheckpoint tblpc = new tblpmcheckpoint();
            tblpc.CreatedBy = 1;
            tblpc.CreatedOn = DateTime.Now;
            tblpc.Isdeleted = 0;
            tblpc.PlantID = Plant;
            tblpc.ShopID = shop;
            tblpc.How = How;
            tblpc.CellID = cell;
            tblpc.frequency = Frequency;
            tblpc.Value = Value;
            tblpc.CheckList = CheckList;
            tblpc.TypeofCheckpoint = TypeOfCheckPoint;
            db.tblpmcheckpoints.Add(tblpc);
            db.SaveChanges();

            return Json(tblpc.pmcpID, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            using (i_facilityEntities1 db = new i_facilityEntities1())
            {
                var tblpm = db.tblpmcheckpoints.Where(m => m.pmcpID == id && m.Isdeleted == 0).FirstOrDefault();
                if (tblpm == null)
                {
                    return HttpNotFound();
                }
                PmCheckPoint pm = new PmCheckPoint();
                pm.pmCheckPoint = tblpm;
                ViewBag.plant = new SelectList(db.tblplants.ToList().Where(p => p.IsDeleted == 0), "PlantID", "PlantName", tblpm.PlantID).ToList();
                ViewBag.shop = new SelectList(db.tblshops.ToList().Where(d => d.IsDeleted == 0), "ShopId", "ShopName", tblpm.ShopID).ToList();
                ViewBag.cell = new SelectList(db.tblcells.ToList().Where(d => d.IsDeleted == 0), "CellID", "CellName", tblpm.CellID).ToList();
                return View(pm);
            }
        }
            public string update(int plant,int shop,int cell,string typeofcheckpoint,string value,string frequency,int pmcpid,string checklist,string How)
        {
            string res = "";
            var tblpc = db.tblpmcheckpoints.Find(pmcpid);
           
            tblpc.Isdeleted = 0;
            tblpc.PlantID = plant;
            tblpc.ShopID = shop;
            tblpc.CellID = cell;
            tblpc.pmcpID = pmcpid;
            tblpc.frequency = frequency;
            tblpc.Value = value;
            tblpc.How = How;
            tblpc.CheckList = checklist;
            tblpc.TypeofCheckpoint = typeofcheckpoint;
            tblpc.ModifiedBy = ViewBag.roleid;
            tblpc.ModifiedOn = DateTime.Now;
            db.Entry(tblpc).State = EntityState.Modified;
            db.SaveChanges();
            res = "Success";
            return res;
        }

        public JsonResult GetcheckpointById(int Id)
        {
            using (i_facilityEntities1 db = new i_facilityEntities1())
            {
                var Data = db.tblpmcheckpoints.Where(m => m.CellID == Id).Select(m => new { pmcpid= m.pmcpID, plant=m.PlantID, shop=m.ShopID, cell=m.CellID, typeofcheckpoint = m.TypeofCheckpoint, frequency = m.frequency, value = m.Value, checklist = m.CheckList,how = m.How });
                return Json(Data, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult FetchCell(int SID)
        {
            using (i_facilityEntities1 db = new i_facilityEntities1())
            {
                var CellData = (from row in db.tblcells
                                where row.IsDeleted == 0 && row.ShopID == SID
                                select new { Value = row.CellID, Text = row.CelldisplayName }).ToList();
                return Json(CellData, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult Delete(int id)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            int UserID = Convert.ToInt32(Session["UserId"]);
            String Username = Session["Username"].ToString();
            //Getting all the details of that particular id in PMCheckPoint table
            tblpmcheckpoint tblmc = db.tblpmcheckpoints.Find(id);

            using (i_facilityEntities1 db = new i_facilityEntities1())
            {
                //Getting all the details of that particular id in PMCheckList table
                var data = db.tblpmchecklists.Where(m => m.pmcpID == id && m.Isdeleted == 0).ToList();
                foreach (var row in data)
                {
                    //deleting the perticular row of that id in tblPMCheckList table
                    row.Isdeleted = 1;
                    db.SaveChanges();
                }
                //And deleting the row present in tblPMCheckPoint table
                
            }
            tblmc.Isdeleted = 1;
            db.SaveChanges();
                return RedirectToAction("Index");
            
        }

        public JsonResult DeleteData(int id = 0)
        {
            var tblpm = db.tblpmcheckpoints.Where(m => m.pmcpID == id).FirstOrDefault();
            tblpm.Isdeleted = 1;
            tblpm.ModifiedBy = 1;
            tblpm.ModifiedOn = DateTime.Now;
            db.Entry(tblpm).State = EntityState.Modified;
            db.SaveChanges();
            return Json(tblpm.pmcpID, JsonRequestBehavior.AllowGet);
        }

    }
}

I_Facility/Views/PmCheckPoint/Edit.cshtml
@model I_Facility.ServerModel.PmCheckPoint
@{
    ViewBag.Title = "CheckPoint";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container body">
    <div class="main_container">
        <div class="right_col" role="main">
            <div class="">

                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>CheckPoint Details</h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li>
                                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                @using (Html.BeginForm("Edit", "PmCheckPoint", FormMethod.Post))
                                {

                                    <div class="x_content">
                                        <form class="form-horizontal form-label-left" novalidate>
                                            <div class="row row-space">
                                                @Html.HiddenFor(model => model.pmCheckPoint.pmcpID, new { @id = "pmcfID" })
                                                <label class="col-sm-1 control-label">Plant</label>
                                                <div class="col-sm-3">
                                                    @Html.HiddenFor(model => model.pmCheckPoint.PlantID, new { @id = "plantID" })

                                                    @Html.DropDownList("plant", null, "--Select plant--", new { @id = "plant", @class = "form-control", @name = "plant", @required = "required", @value = "@ViewData['plant']" })
                                                </div>
                                                <label class="col-sm-1 control-label">Shop</label>
                                                <div class="col-sm-3">
                                                    @Html.HiddenFor(model => model.pmCheckPoint.ShopID, new { @id = "shopID" })
                                                    @Html.DropDownList("shop", null, "--Select Shop--", new { @id = "shop", @class = "form-control", @name = "shop", @required = "required", @value = "@ViewData['shop']" })
                                                </div>
                                                <label class="col-sm-1 control-label">Cell</label>
                                                <div class="col-sm-3">
                                                    @Html.HiddenFor(model => model.pmCheckPoint.CellID, new { @id = "CellID" })
                                                    @Html.DropDownList("cell", null, "--Select Cell--", new { @id = "cell", @class = "form-control", @name = "cell", @required = "required", @value = "@ViewData['cell']" })
                                                </div>
                                                <label class="col-sm-1 control-label">Type Of CheckPoint</label>
                                                <div class="col-sm-3">

                                                    @Html.TextBoxFor(model => model.pmCheckPoint.TypeofCheckpoint, new { @id = "TypeOfCheckPoint", @class = "form-control", @name = "TypeOfCheckPoint", style = "width:89.7%", @placeholder = "Enter TypeOfCheckPoint", @required = "required" })
                                                </div>
                                                <label class="col-sm-1 control-label">Check List</label>
                                                <div class="col-sm-3">
                                                    @Html.TextBoxFor(model => model.pmCheckPoint.CheckList, new { @id = "CheckList", @class = "form-control", @name = "CheckList", style = "width:89.7%", @placeholder = "Enter CheckList", @required = "required" })
                                                </div>
                                                <label class="col-sm-1 control-label">How</label>
                                                <div class="col-sm-3">
                                                    @Html.TextBoxFor(model => model.pmCheckPoint.How, new { @id = "How", @class = "form-control", @name = "How", style = "width:89.7%", @placeholder = "Enter How", @required = "required" })
                                                </div>
                                                <label class="col-sm-1 control-label">Value</label>
                                                <div class="col-sm-3">
                                                    @Html.TextBoxFor(model => model.pmCheckPoint.Value, new { @id = "Value", @class = "form-control", @name = "Value", style = "width:89.7%", @placeholder = "Enter Value", @required = "required" })
                                                </div>
                                                <label class="col-sm-1 control-label">Frequency</label>
                                                <div class="col-sm-3">
                                                    @Html.TextBoxFor(model => model.pmCheckPoint.frequency, new { @id = "Frequency", @class = "form-control", @name = "Frequency", style = "width:89.7%", @placeholder = "Enter Frequency", @required = "required" })

                                                </div>
                                            </div>
                                        </form>
                                        <div class="generate-btn">
                                            <a id="" href="/PmCheckPoint/Index" type="submit" class="btn btn-new"><i class="fa fa-chevron-left" aria-hidden="true"></i>&nbsp;Back</a>
                                            <button type="submit" class="btn btn-new float-right updatebtn"><i class="fa fa-floppy-o" aria-hidden="true"></i>&nbsp;Update</button>

                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    @Html.HiddenFor(model => model.pmCheckPoint.CreatedOn, new { @id = "CreatedOn" })
    @Html.HiddenFor(model => model.pmCheckPoint.CreatedBy, new { @id = "CreatedBy" })
    @Html.HiddenFor(model => model.pmCheckPoint.Isdeleted, new { @id = "IsDeleted" })
    <script src="~/js/jquery-2.1.4.min.js"></script>
    @if (TempData["Message"] != null)
    {
        <input type="hidden" id="Message" value="@TempData["Message"]" />
        <script type="text/javascript">
            $(function () {
                var message = $("#Message").val();
                if (message != "") {
                    $("#errorMessage").html(message);


                }
            });
        </script>
    }

    <script>
        $(document).on('click', '.updatebtn', function (e) {
            var pmcpid = $("#pmcfID").val();
            var plant = $("#plant").val();
            var shop = $("#shop").val();
            var cell = $("#cell").val();
            var typeofcheckpoint = $("#TypeOfCheckPoint").val();
            var checklist = $("#CheckList").val();
            var How = $("#How").val();
            var frequency = $("#Value").val();
            var value = $("#Frequency").val();
            $.get("/PmCheckPoint/update", {
                plant: plant, shop: shop, cell: cell, typeofcheckpoint: typeofcheckpoint, value: value, How: How,
                frequency: frequency, pmcpid: pmcpid, checklist: checklist
            }, function (res) {
                if (res != null) {
                    window.location.href = "/PmCheckPoint/Index";
                }
                window.location.href = "/PmCheckPoint/Index";
            });

        });
    </script>
    <script>
        $(".control").on("click", function (e) {
            var CellID = $(this).attr("id")
            //alert(CellCategoryID)
            $.getJSON("/PmCheckPoint/GetcheckpointById", { Id: CellID }, function (data) {
                $.each(data, function (index, item) {
                    $("#TypeOfCheckPoint").val((item.typeofcheckpoint));


                });
            }
                                            }


    </script>
    <script>
        $(document).ready(function (e) {

                   // $(".BottelneckMachine").on("click", function (e) {
            var pmcpid = $("#pmcfID").attr("id");
                    $.getJSON("/PmCheckPoint/GetcheckpointById", { pmcpid: pmcpid }, function (data) {
                        $.each(data, function (index, item) {
                            //$("#pmcfID").val(item.pmc
                            //$("#plant").val(item.plant);
                            //$("#shop").val((item.shop));
                            //$("#cell").val((item.cell));
                            //$("#TypeOfCheckPoint").val((item.TypeOfCheckPoint));pid);
                            //$("#CheckList").val((item.CheckList));
                            //$("#How").val((item.how));
                            //$("#Value").val((item.Value));
                            //$("#Frequency").val((item.Frequency));

                            var PID = item.plant;
                            $.getJSON("/PmCheckList/FetchShop", { PID: PID }, function (data) {
                                $("#shop").empty();
                                $("#shop").append("<option value = ''> --Select shop-- </option>");
                                $.each(data, function (index, item) {
                                    $("#shop").append("<option value = '" + item.Value + "'>" + item.Text + "</option>");
                                });
                                $("#shop").val(item.shop);
                            });


                            var SID = item.shop;
                            $.getJSON("/PmCheckList/FetchCell", { SID: SID }, function (data) {
                                $("#cell").empty();
                                $("#cell").append("<option value = ''> --Select cell-- </option>");
                                $.each(data, function (index, item) {
                                    $("#cell").append("<option value = '" + item.Value + "'>" + item.Text + "</option>");
                                });
                                $("#cell").val(item.cell);
                            });
                            //var PID = $(this).val();
                            //$.getJSON("/BottelNeckMachine/FetchShop", { PID: PID }, function (data) {
                            //    $("#shop").empty();
                            //    $("#shop").append("<option value = ''> --Select shop-- </option>");
                            //    $.each(data, function (index, item) {
                            //        $("#shop").append("<option value = '" + item.Value + "'>" + item.Text + "</option>");
                            //    });
                            //    $("#shop").val(item.DepartmentId);
                            //});

                            //$("#shop").on("change", function (e) {
                            //    var SID = $(this).val();
                            //    var PID = $("#plant").val();
                            //    $.getJSON("/BottelNeckMachine/FetchCell", { PID: PID, SID: SID }, function (data) {
                            //        $("#cell").empty();
                            //        $("#cell").append("<option value = ''> --Select Cell-- </option>");
                            //        $.each(data, function (index, item) {
                            //            $("#cell").append("<option value = '" + item.Value + "'>" + item.Text + "</option>");
                            //        });
                            //        $("#cell").val(item.cellID);
                            //    });
                            //});


                        });
                    });
                    return false;
            });
    </script>

I_Facility/Views/PmCheckPoint/Index.cshtml
@model I_Facility.ServerModel.PmCheckPoint
    @{ 
    ViewBag.Title = "CheckPoint";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container body">
    <div class="main_container">
        <div class="right_col" role="main">
            <div class="">

                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>CheckPoint Details</h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li>
                                        <span>
                                            @Html.ActionLink(" Add New", "Create", "PmCheckPoint", new { @class = "btn btn-default" }, new { @style = "margin-top: 10px; padding-top:7px;", @class = "btn btn-default fa fa-plus-square" })
                                            @*<a role="button" href="create-shift-detail.html" class="btn btn-default " style="margin-top: 10px;"><i class="fa fa-plus-square" aria-hidden="true"></i>&nbsp;Add New</a>*@
                                        </span>
                                    </li>
                                    <li>
                                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <table id="datatable-fixed-header" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Plant Name</th>
                                            <th>Shop Name</th>
                                            <th>Cell Name</th>
                                            <th>Type Of CheckPoint</th>
                                            <th>CheckList Data</th>
                                            <th>Frequency</th>
                                            <th>Value</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.pmCheckPointlist)
                                        {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.tblplant.PlantName)</td>
                                            <td>@Html.DisplayFor(modelItem => item.tblshop.ShopName)</td>
                                            <td>@Html.DisplayFor(modelItem => item.tblcell.CellName)</td>
                                            <td>@Html.DisplayFor(modelItem => item.TypeofCheckpoint)</td>
                                            <td>@Html.DisplayFor(modelItem => item.CheckList)</td>
                                            <td>@Html.DisplayFor(modelItem => item.frequency)</td>
                                            <td>@Html.DisplayFor(modelItem => item.Value)</td>
                                            <td>
                                                <ul class="actionbtnn">
                                                    @*@Html.ActionLink(" ", "Edit", new { id = item.MSDID }, new { @class = " blue  btn-lg fa fa-edit", @style = "color:white;text-decoration:none" })*@
                                                    <li class="actionbtn"><a href="@Url.Action("Edit", "PmCheckPoint", new {id = item.pmcpID })" id="@(@item.pmcpID)" style="margin-top:0px;" class="btn btn-round btn-info" data-title="Edit" role="button"><i class="fa fa-pencil fa-lg" aria-hidden="true" data-placement="top" data-toggle="tooltip" title="Edit PmCheckPoint detail" style="line-height: 24px;"></i></a></li>

                                                    @*<li class="actionbtn"><button class="btn btn-round btn-danger" data-title="Edit" data-toggle="modal" data-target="#delete-plant"><i class="fa fa-trash fa-lg" aria-hidden="true" data-placement="top" data-toggle="tooltip" title="Delete Shift detail"></i></button></li>*@
                                                    <li class="actionbtn"><button class="btn btn-round btn-danger deleteItem" data-id="@item.pmcpID" style="margin-top:0px;" onclick="deleteTargetName('@item.TypeofCheckpoint')" data-title="Edit" data-toggle="modal" data-target="#delete-plant"><i class="fa fa-trash fa-lg" aria-hidden="true" data-placement="top" data-toggle="tooltip" title="Delete PmCheckPoint details"></i></button></li>


                                                    <!-- Delete Modal Begin -->

                                                    <div class="modal fade" id="delete-plant" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static" aria-labelledby="myModalLabel">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                                    <h4 class="modal-title" id="myModalLabel"></h4>
                                                                    <div class="x_panel">
                                                                        <div class="x_title">
                                                                            <h5>Delete PmCheckPoint Details</h5>
                                                                        </div>
                                                                        <div class="x_content">
                                                                            <div class="alert alert-danger">
                                                                                <span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Detail?<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label class="alert-danger11">Type of checkpoint:</label>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-danger btnContinueDelete "><span class="glyphicon glyphicon-ok-sign"></span> Yes</button>
                                                                        <button type="button" class="btn btn-info" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </ul>
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->
<script src="~/js/jquery-2.1.4.min.js"></script>
<script>

    function deleteTargetName(productvariant) {
        //alert (productvariant);
        $(".deleteTargetName").empty();
        $(".alert-danger11").html("Type of checkpoint: " +
            productvariant);

    }

    var item_to_delete;
    $(".deleteItem").click(function (e) {
        item_to_delete = $(this).data('id');
        //alert(item_to_delete);
    });
    $('.btnContinueDelete').click(function () {
        window.location = "/PmCheckPoint/Delete/" + "?id=" + item_to_delete;
    });

</script>

<script>
    $(document).ready(function () {
        $("#PlantID").on("change", function (e) {
            debugger
            var PID = $(this).val();
            $.getJSON("/BottelNeckMachine/FetchShop", { PID: PID }, function (data) {
                $("#shop").empty();
                $("#shop").append("<option value=''> --Select Department-- </option>");
                $.each(data, function (index, item) {
                    $("#shop").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
                });
            });
        });

        $("#shop").on("change", function (e) {
            debugger
            var SID = $(this).val();
            var PID = $("#PlantID").val();
            $.getJSON("/BottelNeckMachine/FetchCell", { PID: PID, SID: SID }, function (data) {
                $("#cell").empty();
                $("#cell").append("<option value=''> --Select Cell-- </option>");
                $.each(data, function (index, item) {
                    $("#cell").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
                });
            });
        });
    });
</script>